// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYSW-8V9e61uQ6uy-h4pOYOMx2rmxyL-o',
    appId: '1:424548764282:android:206d6e4bdc76d9386e09c3',
    messagingSenderId: '424548764282',
    projectId: 'finalchat-b9e21',
    storageBucket: 'finalchat-b9e21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACCPpnoL6M3A4Gu3WkTMZoFpupoKA2VyA',
    appId: '1:424548764282:ios:366a263e6badb14b6e09c3',
    messagingSenderId: '424548764282',
    projectId: 'finalchat-b9e21',
    storageBucket: 'finalchat-b9e21.appspot.com',
    iosBundleId: 'com.harshRajpurohit.weChat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtcGxktNMZK5oH6dyCb4Vi94Ib29NOAz0',
    appId: '1:424548764282:web:2dd61105663b2aea6e09c3',
    messagingSenderId: '424548764282',
    projectId: 'finalchat-b9e21',
    authDomain: 'finalchat-b9e21.firebaseapp.com',
    storageBucket: 'finalchat-b9e21.appspot.com',
  );
}
